Repository Golden-Doodle/CU-MapNav, pull requests merged in 2025-02, with the labels that each got.

#60 Update tests
  expo-app/.gitignore
  expo-app/app/__tests__/index.test.tsx
  expo-app/app/__tests__/test-utils.ts
  expo-app/app/components/BottomNavigation/BottomNavigation.tsx
  expo-app/app/components/BottomNavigation/__tests__/BottomNavigation.test.tsx
  expo-app/app/components/ButtonSection/__tests__/ButtonSection.test.tsx
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/components/CampusMap/modals/BuildingInfoModal.tsx
  expo-app/app/components/CampusMap/modals/__tests__/BuildingInfoModal.test.tsx
  expo-app/app/components/CampusMap/modals/__tests__/NextClassModal.test.tsx
  expo-app/app/components/Header/__tests__/Header.test.tsx
  expo-app/app/components/HottestSpots/__tests__/HottestSpots.test.tsx
  expo-app/app/components/QuickShortcuts/__tests__/QuickShortcuts.test.tsx
  expo-app/app/components/SearchBar/SearchBar.tsx
  expo-app/app/components/SearchBar/__tests__/SearchBar.test.tsx
  expo-app/app/components/ShuttleSchedule/__tests__/ShuttleSchedule.test.tsx
  expo-app/app/index.tsx
  expo-app/app/screens/Home/__tests__/CampusMapScreen.test.tsx
  expo-app/app/screens/Home/__tests__/HomeMenuScreen.test.tsx
  expo-app/app/screens/Home/__tests__/HomePageScreen.test.tsx
  expo-app/app/screens/Home/__tests__/ShuttleScheduleScreen.test.tsx
  expo-app/app/screens/Home/__tests__/StudySpotsScreen.test.tsx
  expo-app/jest.setup.js
  expo-app/package-lock.json
  expo-app/package.json
  expo-app/tsconfig.json
Labels: documentation, tests

#61 Implementing google calendar
  expo-app/app/_layout.tsx
  expo-app/app/components/CampusMap/modals/NextClassModal.tsx
  expo-app/app/components/Header/Header.styles.ts
  expo-app/app/components/Header/Header.tsx
  expo-app/app/components/Header/NextClassComponent.tsx
  expo-app/app/components/Header/__tests__/Header.test.tsx
  expo-app/app/components/Header/__tests__/NextClassComponent.test.tsx
  expo-app/app/contexts/AuthContext.tsx
  expo-app/app/contexts/__tests__/AuthContext.test.tsx
  expo-app/app/index.tsx
  expo-app/app/screens/Home/HomePageScreen.tsx
  expo-app/app/services/GoogleCalendar/fetchingUserCalendarData.ts
  expo-app/app/services/GoogleCalendar/readMe.md
  expo-app/app/utils/types.ts
  expo-app/jest.setup.js
Labels: enhancement

#65 Optimize route button functionality
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/CampusMapNavTab.tsx
  expo-app/app/components/CampusMap/data/buildingData.ts
  expo-app/app/components/CampusMap/data/customMarkerData.ts
  expo-app/app/components/CampusMap/modals/NextClassModal.tsx
  expo-app/app/components/Header/Header.styles.ts
  expo-app/app/components/Header/Header.tsx
  expo-app/app/components/Header/NextClassComponent.tsx
  expo-app/app/contexts/AuthContext.tsx
  expo-app/app/screens/Home/CampusMapScreen.tsx
  expo-app/app/screens/Home/HomePageScreen.tsx
  expo-app/app/services/GoogleCalendar/fetchingUserCalendarData.ts
  expo-app/app/utils/directions.ts
  expo-app/app/utils/types.ts
  expo-app/package-lock.json
Labels: enhancement, back-end

#66 UI screens
  expo-app/app/_layout.tsx
  expo-app/app/about.tsx
  expo-app/app/account.tsx
  expo-app/app/campus-map.tsx
  expo-app/app/index.tsx
  expo-app/app/language.tsx
  expo-app/app/menu.tsx
  expo-app/app/report.tsx
  expo-app/app/schedule.tsx
  expo-app/app/services.tsx
  expo-app/app/settings.tsx
  expo-app/app/study-spots.tsx
  expo-app/app/sum_example.tsx
  expo-app/babel.config.js
  expo-app/components/BottomNavigation/BottomNavigation.styles.ts
  expo-app/components/BottomNavigation/BottomNavigation.tsx
  expo-app/components/ButtonSection/ButtonSection.styles.ts
  expo-app/components/ButtonSection/ButtonSection.tsx
  expo-app/components/Header/Header.styles.ts
  expo-app/components/Header/Header.tsx
  expo-app/components/HottestSpots/HottestSpots.tsx
  expo-app/components/QuickShortcuts/QuickShortcuts.tsx
  expo-app/components/ReportForm/ReportForm.tsx
  expo-app/components/ReportHeader/ReportHeader.tsx
  expo-app/components/SearchBar/SearchBar.tsx
  expo-app/components/ServicesHeader/ServicesHeader.tsx
  expo-app/components/SettingsHeader.tsx
  expo-app/components/ShuttleSchedule/ShuttleSchedule.tsx
  expo-app/components/TimePicker.tsx
  expo-app/tsconfig.json
Labels: enhancement, front-end

#67 UI new screens
  expo-app/app/components/BottomNavigation/BottomNavigation.tsx
  expo-app/app/components/Report/ReportForm.tsx
  expo-app/app/components/Report/ReportHeader.tsx
  expo-app/app/components/Settings/SettingsHeader.tsx
  expo-app/app/components/ShuttleSchedule/ShuttleHeader.tsx
  expo-app/app/components/ShuttleSchedule/ShuttleSchedule.tsx
  expo-app/app/components/TimePicker.tsx
  expo-app/app/index.tsx
  expo-app/app/screens/Home/HomeMenuScreen.tsx
  expo-app/app/screens/Home/HomePageScreen.tsx
  expo-app/app/screens/Home/__tests__/ShuttleScheduleScreen.test.tsx
  expo-app/app/screens/Report/ReportScreen.tsx
  expo-app/app/screens/Settings/AccountSettingsScreen.tsx
  expo-app/app/screens/Settings/SettingsScreen.tsx
  expo-app/app/screens/Settings/SupportScreen.tsx
  expo-app/app/screens/Shuttle/ShuttleScheduleScreen.tsx
  expo-app/app/screens/Shuttle/ShuttleScreen.tsx
  expo-app/app/screens/StudySpots/StudySpotScreen.tsx
  expo-app/babel.config.js
  expo-app/package-lock.json
  expo-app/package.json
Labels: enhancement, front-end

#75 Fix cicd pipeline
  .github/workflows/ci-cd.yml
  expo-app/app/components/ButtonSection/__tests__/ButtonSection.test.tsx
  expo-app/app/components/SearchBar/SearchBar.tsx
  expo-app/app/components/SearchBar/__tests__/SearchBar.test.tsx
  expo-app/app/components/ShuttleSchedule/ShuttleSchedule.tsx
  expo-app/app/components/ShuttleSchedule/__tests__/ShuttleSchedule.test.tsx
  expo-app/app/contexts/__tests__/AuthContext.test.tsx
  expo-app/app/screens/Home/__tests__/CampusMapScreen.test.tsx
Labels: bug
