Repository Golden-Doodle/CU-MapNav, pull requests merged in 2025-03, with the labels that each got.

#92 Unit tests for new UI screens and existing components/screens
  expo-app/app/__tests__/__snapshots__/layout.test.tsx.snap
  expo-app/app/__tests__/index.test.tsx
  expo-app/app/__tests__/layout.test.tsx
  expo-app/app/components/BottomNavigation/BottomNavigation.tsx
  expo-app/app/components/BottomNavigation/__tests__/BottomNavigation.test.tsx
  expo-app/app/components/CampusMap/CustomMarker.tsx
  expo-app/app/components/CampusMap/HamburgerWidget.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMapNavTab.test.tsx
  expo-app/app/components/CampusMap/__tests__/CustomMarker.test.tsx
  expo-app/app/components/CampusMap/__tests__/HamburgerWidget.test.tsx
  expo-app/app/components/CampusMap/data/fakeGoogleCalendarData.ts
  expo-app/app/components/CampusMap/modals/BuildingInfoModal.tsx
  expo-app/app/components/CampusMap/modals/NextClassModal.tsx
  expo-app/app/components/CampusMap/modals/SearchModal.tsx
  expo-app/app/components/CampusMap/modals/TransitModal.tsx
  expo-app/app/components/CampusMap/modals/__tests__/BuildingInfoModal.test.tsx
  expo-app/app/components/CampusMap/modals/__tests__/NavigateModal.test.tsx
  expo-app/app/components/CampusMap/modals/__tests__/NextClassModal.test.tsx
  expo-app/app/components/CampusMap/modals/__tests__/SearchModal.test.tsx
  expo-app/app/components/CampusMap/modals/__tests__/TransitModal.test.tsx
  expo-app/app/components/Header/Header.tsx
  expo-app/app/components/Header/NextClassComponent.tsx
  expo-app/app/components/Header/__tests__/Header.test.tsx
  expo-app/app/components/Header/__tests__/NextClassComponent.test.tsx
  expo-app/app/components/Report/ReportForm.tsx
  expo-app/app/components/Report/ReportHeader.tsx
  expo-app/app/components/Report/__tests__/ReportForm.test.tsx
  expo-app/app/components/Report/__tests__/ReportHeader.test.tsx
  expo-app/app/components/Settings/SettingsHeader.tsx
  expo-app/app/components/ShuttleSchedule/ShuttleSchedule.tsx
  expo-app/app/components/ShuttleSchedule/__tests__/ShuttleSchedule.test.tsx
  expo-app/app/components/TimePicker/TimePicker.tsx
  expo-app/app/components/TimePicker/__tests__/TimePicker.test.tsx
  expo-app/app/index.tsx
  expo-app/app/screens/Home/__tests__/HomePageScreen.test.tsx
  expo-app/app/screens/Home/__tests__/ShuttleScheduleScreen.test.tsx
  expo-app/app/screens/Report/__tests__/ReportScreen.test.tsx
  expo-app/app/screens/Settings/AccountSettingsScreen.tsx
  expo-app/app/screens/Settings/ScheduleScreen.tsx
  expo-app/app/screens/Settings/SettingsScreen.tsx
  expo-app/app/screens/Settings/SupportScreen.tsx
  expo-app/app/screens/Settings/__tests__/AccountSettingsScreen.test.tsx
  expo-app/app/screens/Settings/__tests__/ScheduleScreen.test.tsx
  expo-app/app/screens/Settings/__tests__/SettingsScreen.test.tsx
  expo-app/app/screens/Settings/__tests__/SupportScreen.test.tsx
  expo-app/app/screens/Shuttle/ShuttleScreen.tsx
  expo-app/app/screens/Shuttle/__tests__/ShuttleScreen.test.tsx
  expo-app/app/screens/StudySpots/__tests__/StudySpotScreen.test.tsx
  expo-app/app/services/ConcordiaShuttle/ConcordiaApiShuttle.ts
  expo-app/app/services/ConcordiaShuttle/__tests__/ConcordiaApiShuttle.test.tsx
  expo-app/app/services/GoogleCalendar/__tests__/fetchingUserCalendarData.test.tsx
  expo-app/app/utils/__tests__/directions.test.tsx
  expo-app/app/utils/__tests__/helperFunction.test.tsx
  expo-app/app/utils/directions.ts
Labels: tests

#98 added description to building data
  expo-app/app/components/CampusMap/data/buildingData.ts
Labels: enhancement

#107 Unit test fix
  expo-app/app/components/CampusMap/modals/SearchModal.tsx
  expo-app/app/components/CampusMap/modals/TransitModal.tsx
  expo-app/app/components/CampusMap/modals/__tests__/NextClassModal.test.tsx
  expo-app/app/components/CampusMap/modals/__tests__/SearchModal.test.tsx
  expo-app/app/components/CampusMap/modals/__tests__/TransitModal.test.tsx
  expo-app/app/components/Report/__tests__/ReportForm.test.tsx
  expo-app/app/screens/Settings/AccountSettingsScreen.tsx
  expo-app/app/screens/Settings/__tests__/AccountSettingsScreen.test.tsx
Labels: bug

#119 Increase Coverage to 80%>
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/CampusMapNavTab.tsx
  expo-app/app/components/CampusMap/CustomMarker.tsx
  expo-app/app/components/CampusMap/HamburgerWidget.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMapNavTab.test.tsx
  expo-app/app/components/CampusMap/__tests__/CustomMarker.test.tsx
  expo-app/app/components/CampusMap/__tests__/HamburgerWidget.test.tsx
  expo-app/app/components/CampusMap/modals/BuildingInfoModal.tsx
  expo-app/app/components/CampusMap/modals/NextClassModal.tsx
  expo-app/app/components/CampusMap/modals/SearchModal.tsx
  expo-app/app/components/CampusMap/modals/TransitModal.tsx
  expo-app/app/components/CampusMap/modals/__tests__/BuildingInfoModal.test.tsx
  expo-app/app/components/CampusMap/modals/__tests__/NextClassModal.test.tsx
  expo-app/app/components/CampusMap/modals/__tests__/SearchModal.test.tsx
  expo-app/app/components/CampusMap/modals/__tests__/TransitModal.test.tsx
  expo-app/app/screens/Settings/__tests__/AccountSettingsScreen.test.tsx
  expo-app/app/utils/__tests__/directions.test.tsx
  expo-app/package-lock.json
  expo-app/package.json
Labels: bug, tests

#121 Fix sonar qube
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/components/CampusMap/modals/NextClassModal.tsx
  expo-app/app/components/CampusMap/modals/TransitModal.tsx
  expo-app/app/components/CampusMap/modals/__tests__/NextClassModal.test.tsx
  expo-app/app/contexts/__tests__/AuthContext.test.tsx
  expo-app/app/screens/Settings/__tests__/SettingsScreen.test.tsx
Labels: bug, tests, sonar-qube

#129 Refactoring data
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/CustomMarker.tsx
  expo-app/app/components/CampusMap/data/buildingData.ts
  expo-app/app/components/CampusMap/data/customMarkerData.ts
  expo-app/app/components/CampusMap/data/initialRegion.ts
  expo-app/app/components/CampusMap/modals/NextClassModal.tsx
  expo-app/app/components/CampusMap/modals/SearchModal.tsx
  expo-app/app/components/CampusMap/modals/__tests__/NavigateModal.test.tsx
  expo-app/app/components/CampusMap/modals/__tests__/NextClassModal.test.tsx
  expo-app/app/hooks/useSearch.ts
  expo-app/app/utils/__tests__/directions.test.tsx
  expo-app/app/utils/directions.ts
  expo-app/app/utils/types.ts
Labels: enhancement

#127 Current building location
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/components/CampusMap/data/buildingData.ts
Labels: enhancement

#136 Bridging Indoor and Outdoor Navigation
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/CustomMarker.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/components/CampusMap/__tests__/CustomMarker.test.tsx
  expo-app/app/components/CampusMap/modals/BuildingInfoModal.tsx
  expo-app/app/components/CampusMap/modals/TransitModal.tsx
  expo-app/app/components/CampusMap/modals/__tests__/BuildingInfoModal.test.tsx
  expo-app/app/components/CampusMap/modals/__tests__/TransitModal.test.tsx
  expo-app/app/components/IndoorNavigation/IndoorMap.tsx
  expo-app/app/components/IndoorNavigation/__tests__/IndoorMap.test.tsx
  expo-app/app/screens/Home/CampusMapScreen.tsx
  expo-app/assets/images/map-marker.png
  expo-app/assets/images/restaurant-marker.png
  expo-app/package-lock.json
  expo-app/package.json
Labels: enhancement, front-end, back-end

#138 Implement Filter for Outdoor Points of Interest (POIs)
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/CustomMarker.tsx
  expo-app/app/components/CampusMap/RadiusAdjuster.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/components/CampusMap/__tests__/CustomMarker.test.tsx
  expo-app/app/components/CampusMap/__tests__/RadiusAdjuster.test.tsx
  expo-app/app/components/CampusMap/modals/FilterModal.tsx
  expo-app/app/components/CampusMap/modals/__tests__/FilterModal.test.tsx
  expo-app/app/services/GoogleMap/__tests__/googlePlacesService.test.tsx
  expo-app/app/services/GoogleMap/googlePlacesService.tsx
  expo-app/app/utils/types.ts
  expo-app/assets/images/cafe-marker.png
  expo-app/assets/images/washroom-marker.png
Labels: front-end, back-end

#142 US - Add indoor POIs (washrooms, fountains, etc.) for campus building navigation
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/components/IndoorNavigation/IndoorMap.tsx
  expo-app/app/components/IndoorNavigation/Styling/Constants.ts
  expo-app/app/components/IndoorNavigation/Styling/IndoorMap.styles.ts
  expo-app/app/components/IndoorNavigation/Styling/__tests__/markerTemplate.test.tsx
  expo-app/app/components/IndoorNavigation/Styling/markerTemplate.ts
  expo-app/app/components/IndoorNavigation/__tests__/IndoorMap.test.tsx
  expo-app/app/contexts/AuthContext.tsx
  expo-app/app/screens/Home/HomePageScreen.tsx
  expo-app/app/services/GoogleCalendar/__tests__/fetchingUserCalendarData.test.tsx
  expo-app/app/services/GoogleCalendar/fetchingUserCalendarData.ts
Labels: enhancement, front-end, back-end

#152 BUG FIX - The Next Class Modal Now Shows Up When You Press "Optime Route" in The Home Screen
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
Labels: bug

#151 REF - Refactoring Storing of Google Access Token and Homepage Screen
  expo-app/app/contexts/AuthContext.tsx
  expo-app/app/contexts/__tests__/AuthContext.test.tsx
  expo-app/app/hooks/__tests__/useCalendarEvents.test.ts
  expo-app/app/hooks/__tests__/useCampus.test.ts
  expo-app/app/hooks/useCalendarEvents.ts
  expo-app/app/hooks/useCampus.ts
  expo-app/app/screens/Home/HomePageScreen.tsx
  expo-app/app/screens/Home/__tests__/HomePageScreen.test.tsx
  expo-app/app/screens/Settings/__tests__/ScheduleScreen.test.tsx
  expo-app/app/services/GoogleCalendar/__tests__/fetchingUserCalendarData.test.tsx
  expo-app/app/services/GoogleCalendar/fetchingUserCalendarData.ts
  expo-app/app/services/GoogleSignin/__tests__/accessToken.test.ts
  expo-app/app/services/GoogleSignin/accessToken.ts
Labels: refactoring

#154 BUG FIX - Fixed Time Picker Component
  expo-app/app/components/TimePicker/TimePicker.tsx
  expo-app/app/components/TimePicker/__tests__/TimePicker.test.tsx
Labels: bug

#153 BUG FIX - Fixed Services Page by Adding It
  expo-app/app/components/BottomNavigation/BottomNavigation.tsx
  expo-app/app/components/Header/GenericHeader.Styles.ts
  expo-app/app/components/Header/GenericHeader.tsx
  expo-app/app/components/Services/ServicesHeader.tsx
  expo-app/app/components/Settings/SettingsHeader.tsx
  expo-app/app/components/ShuttleSchedule/ShuttleHeader.tsx
  expo-app/app/screens/Services/ServicesScreen.tsx
  expo-app/app/screens/Services/__tests__/ServicesScreen.test.tsx
Labels: bug
