Repository Golden-Doodle/CU-MapNav, pull requests merged in 2025-04, with the labels that each got.

#162 FT - Added Current Building Location Text
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/utils/__tests__/helperFunction.test.tsx
  expo-app/app/utils/helperFunctions.ts
Labels: enhancement, front-end

#158 FT - Add Live Shuttle Icon to Campus Map
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/CustomMarker.tsx
  expo-app/app/components/CampusMap/HamburgerWidget.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/components/CampusMap/__tests__/CustomMarker.test.tsx
  expo-app/app/hooks/__tests__/useLiveShuttleLocations.test.ts
  expo-app/app/hooks/useLiveShuttleLocations.ts
  expo-app/app/services/ConcordiaShuttle/ConcordiaApiShuttle.ts
  expo-app/app/services/ConcordiaShuttle/__tests__/ConcordiaApiShuttle.test.tsx
  expo-app/app/utils/types.ts
  expo-app/assets/images/shuttle-marker.png
  expo-app/maestro-tests/Release 3/ViewLiveShuttleOnMap.yaml
  expo-app/maestro-tests/recordings/Release 3/ViewLiveShuttleOnMap.gif
Labels: enhancement, front-end

#155 FT - Add pressedSearch prop to CampusMap and update routing logic
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/components/SearchBar/SearchBar.tsx
  expo-app/app/components/SearchBar/__tests__/SearchBar.test.tsx
  expo-app/app/screens/Home/CampusMapScreen.tsx
Labels: enhancement, front-end

#163 US - Implemented Indoor Accessbility Button for Routes
  expo-app/app/components/IndoorNavigation/IndoorMap.tsx
  expo-app/app/components/IndoorNavigation/Styling/IndoorMap.styles.ts
  expo-app/app/components/IndoorNavigation/__tests__/IndoorMap.test.tsx
  expo-app/app/services/Mapped-In/MappedInService.tsx
  expo-app/app/services/Mapped-In/__tests__/MappedInService.test.tsx
Labels: documentation, front-end, back-end

#156 FT - Implement Restaurant and Coffee Buttons in HomeScreen
  expo-app/app/components/ButtonSection/ButtonSection.tsx
  expo-app/app/components/ButtonSection/__tests__/ButtonSection.test.tsx
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/components/CampusMap/modals/FilterModal.tsx
  expo-app/app/components/QuickShortcuts/QuickShortcuts.tsx
  expo-app/app/components/QuickShortcuts/__tests__/QuickShortcuts.test.tsx
  expo-app/app/screens/Home/CampusMapScreen.tsx
Labels: enhancement, front-end

#165 REF - Adhere to SonarQube standards
  expo-app/app/components/CampusMap/CampusMap.tsx
  expo-app/app/components/CampusMap/__tests__/CampusMap.test.tsx
  expo-app/app/components/CampusMap/modals/NextClassModal.tsx
  expo-app/app/components/CampusMap/modals/PlaceInfoModal.tsx
  expo-app/app/components/CampusMap/modals/TransitModal.tsx
  expo-app/app/components/Header/NextClassComponent.tsx
  expo-app/app/components/Header/__tests__/NextClassComponent.test.tsx
  expo-app/app/components/IndoorNavigation/DirectionsModal.tsx
  expo-app/app/components/IndoorNavigation/IndoorMap.tsx
  expo-app/app/components/IndoorNavigation/SetBuildingFloorModal.tsx
  expo-app/app/components/IndoorNavigation/__tests__/IndoorMap.test.tsx
  expo-app/app/components/LanguagePicker/LanguagePicker.tsx
  expo-app/app/components/ShuttleSchedule/ShuttleSchedule.tsx
  expo-app/app/components/TimePicker/TimePicker.tsx
  expo-app/app/config/i18n.ts
  expo-app/app/contexts/AuthContext.tsx
  expo-app/app/screens/Chatbot/ChatBotScreen.tsx
  expo-app/app/screens/Settings/AccountSettingsScreen.tsx
  expo-app/app/screens/Settings/ScheduleScreen.tsx
  expo-app/app/screens/Settings/__tests__/AccountSettingsScreen.test.tsx
  expo-app/app/services/Clarity/ClarityService.ts
Labels: refactoring

#182 FT (Bonus feature) - Multi-Stop Planner
  expo-app/app/screens/Home/HomeMenuScreen.tsx
  expo-app/app/screens/Home/__tests__/HomeMenuScreen.test.tsx
  expo-app/app/screens/Schedule/ListModal.tsx
  expo-app/app/screens/Schedule/MultiStopPlanner.tsx
  expo-app/app/screens/Schedule/__tests__/ListModal.test.tsx
  expo-app/app/screens/Schedule/__tests__/MultiStopPlanner.test.tsx
  expo-app/app/services/GoogleMap/__tests__/googlePlacesService.test.tsx
  expo-app/app/services/GoogleMap/googlePlacesService.tsx
  expo-app/maestro-tests/AT/config/AT (7.a) - Given a list of tasks make a plan with directions that minimizes the total walking time and exposure to outdoor weather.yaml
  expo-app/maestro-tests/AT/recordings/AT (7.a) - Given a list of tasks make a plan with directions that minimizes the total walking time and exposure to outdoor weather.gif
  expo-app/maestro-tests/Release 3/AT (7.a) - Given a list of tasks make a plan with directions that minimizes the total walking time and exposure to outdoor weather.yaml
  expo-app/maestro-tests/recordings/Release 3/AT (7.a) - Given a list of tasks make a plan with directions that minimizes the total walking time and exposure to outdoor weather.gif
Labels: enhancement, bonus feature, front-end, back-end
